speed = 727

display_keys = true
key_placement = "inside"
display_counters = true
counter_placement = "outside"

[window]
transparent = true
resizable = false
width = 420
height = 690

[[columns]]
keys = ["KeyQ", "KeyA"]
color = 0xff6376
border_color = 0xff6376

[[columns]]
keys = ["KeyW", "KeyS", "KeyX"]
color = 0x63ffec
border_color = 0x63ffec

[[columns]]
keys = ["LeftBracket"]
color = 0x63ffec
border_color = 0x63ffec

[[columns]]
keys = ["RightBracket"]
color = 0xff6376
border_color = 0xff6376
